# Generated by Django 3.0.6 on 2020-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(max_length=100, null=True, verbose_name='education level'),
        ),
    ]
