# Generated by Django 3.0.6 on 2020-05-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200528_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='is_teacher',
        ),
    ]
