# Generated by Django 3.0.6 on 2020-06-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200601_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
