# Generated by Django 2.1.7 on 2020-05-16 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, verbose_name='book title')),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='')),
                ('published', models.BooleanField(default=False)),
                ('uploadedAt', models.DateField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='course name')),
                ('course_code', models.IntegerField(default=0, unique=True, verbose_name='course code')),
                ('approved', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(null=True, upload_to='dijiElimu/images/')),
                ('blog', models.TextField(default='Hundreds of teachers have gone through our system and become qualified teachers of information technology. Study with us today', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department_code', models.IntegerField(default=0, unique=True, verbose_name='department name')),
                ('blog', models.TextField(default='Hundreds of teachers have gone through our system and become qualified teachers of information technology. Study with us today', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, verbose_name='unit name')),
                ('unit_code', models.IntegerField(default=0, unique=True, verbose_name='unit code')),
                ('student', models.CharField(max_length=100)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('video_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=500)),
                ('Tutor', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('published', models.BooleanField(default=False)),
                ('uploadedAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Department'),
        ),
        migrations.AddField(
            model_name='book',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Unit'),
        ),
    ]
