# Generated by Django 3.0.6 on 2020-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200528_1348'),
        ('users', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='users.StudentProfile'),
        ),
        migrations.AddField(
            model_name='course',
            name='subscriprion',
            field=models.ManyToManyField(related_name='course_subscriptions', to='subscription.Subscription'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='users.TutorProfile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='blog',
            field=models.TextField(default='Hundreds of teachers\n        have gone through our system and\n        become qualified teachers of information\n        technology. Study with us today', max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='blog',
            field=models.TextField(default='Hundreds of teachers have gone\n        through our system and become qualified\n        teachers of information technology. Study with us today', max_length=500),
        ),
    ]
