# Generated by Django 3.0.6 on 2020-06-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_auto_20200530_1338'),
        ('course', '0005_auto_20200530_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_users', through='subscription.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
