# Generated by Django 3.0.6 on 2020-06-03 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20200601_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscribed_users',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(related_name='courses_asigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
