# Generated by Django 3.0.6 on 2020-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('WK', 'Weekly'), ('MT', 'Monthly'), ('FL', 'Full')], max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
