# Generated by Django 3.0.6 on 2020-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='users.StudentProfile'),
        ),
    ]
