# Generated by Django 3.0.6 on 2020-06-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20200601_1325'),
        ('subscription', '0003_auto_20200530_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='students',
        ),
        migrations.AddField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.Course'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='my_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
