# Generated by Django 3.0.6 on 2020-06-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20200601_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
    ]
