# Generated by Django 3.0.6 on 2020-06-02 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_remove_subscription_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriptions',
            field=models.ManyToManyField(related_name='course_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
