# Generated by Django 3.0.6 on 2020-06-03 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200603_0823'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0006_subscription_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('date_subscribed',)},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(related_name='course_subscriprions', to='course.Course'),
        ),
    ]
