# Generated by Django 3.0.6 on 2020-06-03 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_enrolled_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0010_auto_20200603_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='users',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_courses',
            field=models.ManyToManyField(related_name='subscribed_courses', to='course.Course'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
