# Generated by Django 3.0.6 on 2020-06-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20200603_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed_courses',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
    ]
