# Generated by Django 2.1.7 on 2020-05-06 14:22

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('tutor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_title', models.CharField(max_length=100, verbose_name='unit title')),
                ('unit_code', models.IntegerField()),
                ('student', models.CharField(max_length=100)),
                ('grade_type', models.CharField(max_length=1, verbose_name='grade')),
                ('grade_mark', models.IntegerField(verbose_name='grade mark')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'major',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('semester_name', models.CharField(choices=[('Select', 'Select'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], default='Select', max_length=100, verbose_name='semester name')),
            ],
            options={
                'verbose_name_plural': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('second_name', models.CharField(max_length=100, verbose_name='second name')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=100)),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone number')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('second_name', models.CharField(max_length=100, verbose_name='second name')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone number')),
                ('major', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, verbose_name='unit name')),
                ('unit_code', models.IntegerField(verbose_name='unit code')),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('video_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=500)),
                ('Tutor', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijiElimuapi.Major')),
                ('student', models.ManyToManyField(to='dijiElimuapi.Student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(to='dijiElimuapi.Student'),
        ),
    ]
